name          'eoly-profiles'
version       '0.1.0'
source        'https://github.com/eoly/eoly-profiles.git'
author        'eolsen'
license       'Apache 2.0'
summary       'My puppet profiles'
description   ''
project_page  'https://github.com/eoly/eoly-profiles'

dependency 'puppetlabs/stdlib'
